"""Operational controls derived from persistent simulation records."""
from .domain import Engine
from .campaign import Campaign
from .business_views import entity_names
from .distress import Distress
from .service_office import DEPARTMENTS
from .property_operations import SYSTEMS,WORK,systems_for,PropertyOperations


def extension_view(world,page,scope):
    from .executives import records as executive_records
    from .campaign_views import field,hidden,choices,form,table,money
    e=Engine(world);c=Campaign(e);names=entity_names(world)
    businesses=[b for b in world.businesses if c.controlled(b.id)]
    props=[p for p in world.properties if p.owner and c.controlled(p.owner)]
    employees=[emp for emp in world.employments if emp.status=='active' and c.controlled(emp.employer)]
    person_names={p.id:p.name for p in world.people}
    employee_names={emp.id:person_names[emp.person_id] for emp in world.employments}
    from .ui_workflows import role_label
    boptions=choices({b.id:b.name for b in businesses});poptions=choices({p.id:p.name for p in props})
    allprops=choices({p.id:p.name for p in world.properties if p.status=='market' or p in props})
    accounts=choices(names);staff=choices({emp.id:person_names[emp.person_id]+' / '+names[emp.employer]+' / '+next(p.role for p in world.positions if p.id==emp.position_id) for emp in employees})
    view=dict(title=page.replace('_',' ').title(),intro='',forms=[],tables=[],metrics=[],notes=[],links=[],page=page)
    if page=='operations_center':
        view.update(title='Operations and recovery',intro='Cash obligations, operational health and improvements at your current scale. A headquarters is optional.')
        view['tables'].append(table('Financial condition',['Entity','Phase','Overdue','Oldest overdue'],[(name,world.systems.get('distress',{}).get(entity,{}).get('phase','healthy'),money(world.systems.get('distress',{}).get(entity,{}).get('overdue',0)),str(world.systems.get('distress',{}).get(entity,{}).get('age',0))+' days') for entity,name in names.items()]))
        view['tables'].append(table('Dated obligations in selected account',['Account','Source','Due','Remaining'],[(r['account'],r['source'],r['due'],money(r['remaining'])) for r in Distress(e).obligations(scope)]))
        view['tables'].append(table('Operating asset liquidations',['Business','Status','Closing date','Share of book value','Cash received'],[(names.get(p['entity'],p['entity']),p['status'],p['due'],str(p['percent'])+'%',money(p.get('proceeds',0))) for p in world.systems.get('asset_liquidations',[])]))
        view['forms'].append(form('liquidate_assets','Market a closed operation’s remaining assets','Equipment, inventory and customer-loan assets can sell at a loss after 14 days; a buyer can withdraw. Marketing costs $250. Property sales remain in the Property workbench.',[field('entity','Closed operation','','select',choices({b.id:b.name for b in businesses if b.status=='closed'}))]))
        view['forms']+=[form('settle_obligations','Pay recorded obligations','Available cash pays earned wages, suppliers and taxes. Loans and rent retain their counterparties.',[field('entity','Paying account',scope,'select',accounts)]),
            form('negotiate_terms','Request supplier terms','A supplier can accept one 21-day extension or refuse. Debt is never erased.',[field('entity','Borrower',scope,'select',accounts)]),
            form('close_operation','Close operations','Ends employment and accrues severance. Assets, debts and identities remain; owners do not automatically absorb debts.',[field('entity','Business','','select',boptions)]),
            form('local_improvement','Improve one location','Build equipment capacity, quality, automation or customer relationships, or service equipment. No unrelated industry is required.',[field('business_id','Business','','select',boptions),field('kind','Improvement','maintenance','select',choices({k:k.title() for k in ('maintenance','equipment','quality','loyalty','automation')}))])]
        view['forms'].append(form('start_location','Open another location within one company','Same-industry location with separate operating books, shared legal obligations and a consolidated company income-tax assessment. Opening requires funded setup, equipment, working capital and qualified staff.',[field('entity','Existing company','','select',boptions),field('name','New location name'),field('region','County','Rutland County','select',choices({r['id']:r['id'] for r in world.systems['regions']}))]))
        from .collection_views import populate as collection_view
        collection_view(view,world,businesses,scope)
        from .operating_automation import FLAGS
        from .manager_defaults import automation
        for b in businesses:
            policy=automation(world,b)
            fields=[hidden('business_id',b.id)]
            fields += [field(k,'Prefer home-office and owned property specialists' if k=='prefer_internal_property' else k.replace('_',' ').title(),policy.get(k,False),'checkbox') for k in FLAGS]
            fields += [field('location_limit','Maximum same-industry locations',policy.get('location_limit',1),'number',minimum=1,maximum=20),field('loan_limit_dollars','Maximum working-capital proposal ($)',policy.get('loan_limit',1000000)/100,'number',minimum=0),field('flip_limit','Concurrent flips',policy.get('flip_limit',1),'number',minimum=0,maximum=10),field('flip_capital_dollars','Total committed flip capital ($)',policy.get('flip_capital',10000000)/100,'number',minimum=0),field('flip_downside_dollars','Maximum planned downside ($)',policy.get('flip_downside',0)/100,'number',minimum=0),field('service_roles','Services to renew',policy.get('service_roles',[]),'multiselect',choices({k:v[0] for k,v in DEPARTMENTS.items()}))]
            view['forms'].append(form('autonomy_policy',b.name+' — delegated objectives','Routine property work prefers qualified home-office staff, then other owned providers, subject to workload, licenses and county coverage. Clear the internal-specialist preference to use outside providers. Agent preparation consumes staff time before closing fees fall. Financing, property purchases and sales require permission; limits count future commitments.',fields))
        rows=[]
        for b in businesses:
            s=world.systems.get('industry_state',{}).get(b.id,{})
            rows.append((b.name,b.industry,str(s.get('equipment_condition',100))+'/100',str(s.get('inventory_age',0))+' days',s.get('finished_units',0),str(s.get('rework_minutes',0))+' minutes',s.get('customer_relationships',50)))
        view['tables'].append(table('Industry operations',['Business','Industry','Equipment','Inventory age','Finished goods','Rework','Customer relationships'],rows))
        if world.systems.get('campaign_outcome'):view['notes'].append('Campaign ended: '+world.systems['campaign_outcome']['reason'])
        view['tables'].append(table('Locations within one legal company',['Operating location','Legal company','Shared unpaid obligation'],[(names.get(uid,uid),names.get(r['company'],r['company']),money(r['shared_obligations'])) for uid,r in world.systems.get('operating_locations',{}).items() if c.controlled(uid)]))
        view['tables'].append(table('Executive scope',['Employee','Designation','Businesses','Authority key'],[(person_names.get(next((e.person_id for e in employees if e.id==r['employment_id']),''),r['employment_id']),r['role'],', '.join(names.get(b,b) for b in r['business_ids']),r['authority_key']) for r in executive_records(world)]))
        view['forms'].append(form('executive_assign','Appoint optional executive leadership','Home Office Directors and VPs remain employees with one primary reporting line. Each business takes 30 minutes per working day. Appointment includes the expected pay increase: 15% for a Home Office Director or 25% for a VP, plus 5% per additional business; prior compensated responsibility counts toward this. The review shows future payroll costs for the existing employer.',[field('employment_id','Employee','','select',staff),field('role','Designation','home_office_director','select',choices({'home_office_director':'Home Office Director','division_vp':'Division VP','corporate_services_vp':'VP of Corporate Services'})),field('business_ids','Businesses in scope (select several)',[],'multiselect',boptions),field('limit_dollars','Resource limit ($)',10000,'number',minimum=0)]))
        for record in executive_records(world):
            from .authority import GROUPS
            contract=world.systems.get('authority_contracts',{}).get(record['authority_key'],{})
            view['forms'].append(form('authority_contract','Grant authority to '+record['role']+' '+record['employment_id'],'Monthly resource allocation is charged to the same authority ledger as managers. The actual parent must supply cash; incoming revenue is not assumed.',[hidden('target',record['authority_key']),field('objective','Objective',contract.get('objective','balanced'),'select',choices({'balanced':'Maintain working capital','growth':'Fund approved growth','preserve_cash':'Prioritize cash and collection'})),field('transaction_limit_dollars','Transaction ceiling ($)',contract.get('transaction_limit',10000*100)/100,'number',minimum=0),field('period_limit_dollars','Monthly commitment limit ($)',contract.get('period_limit',30000*100)/100,'number',minimum=0),field('cash_reserve_dollars','Parent cash reserve ($)',contract.get('cash_reserve',10000*100)/100,'number',minimum=0),field('horizon','Reserve forecast days',contract.get('horizon',30),'number',minimum=1,maximum=90),field('parent','Parent authority contract',contract.get('parent') or '','select',choices({'':'Player grants authority',**{key:key for key in world.systems.get('authority_contracts',{}) if key!=record['authority_key']}})),field('regions','Permitted counties, comma separated',','.join(contract.get('regions',sorted({b.region for b in businesses if b.id in record['business_ids']}))))]+[field(group,group.replace('_',' ').title(),contract.get('actions',{}).get(group,'approval' if group in ('staffing','pricing','expansion','financing','property_acquisition','asset_sales') else 'allow'),'select',choices({'allow':'Allowed','approval':'Player approval','prohibit':'Prohibited'})) for group in GROUPS]))
    elif page=='home_office':
        view.update(title='Home office services',intro='Prioritized work competes for qualified employee time. Internal, outside and mixed delivery are available without a mandatory headquarters.')
        view['tables'].append(table('Departments and queue capacity',['Provider / department','Assigned employees','Counties','Expertise','Capacity (min)','Used (min)','Unallocated (min)'],[(names.get(d['provider'],d['provider'])+' / '+role_label(d['role']),', '.join(employee_names.get(uid,uid) for uid in d['staff']) or 'All qualified role staff',', '.join(d['regions']),', '.join(d['industries']),d.get('last_capacity',0),d.get('last_used',0),max(0,d.get('last_capacity',0)-d.get('last_used',0))) for d in world.systems.get('departments',{}).values()]))
        view['tables'].append(table('Service work queue and digest',['ID / service','Recipient','Provider / mode / assigned staff','Priority / deadline','Effort remaining','Status','Costs / work product'],[(t['id']+' / '+t.get('product',t['department']).replace('_',' '),names.get(t['recipient'],t['recipient']),names.get(t['provider'],'Outside specialists' if t['provider']=='outside' else t['provider'])+' / '+t['mode']+' / '+(', '.join(employee_names.get(uid,uid) for uid in t['staff']) or ('Outside specialist team' if t['provider']=='outside' else 'Qualified department staff')),str(t['priority'])+' / '+t['due'],str(t['remaining'])+' min',t['status'],money(t['internal_cost'])+' internal; '+money(t['outside_cost'])+' outside expense; '+money(t.get('prepaid',0))+' prepaid remaining. '+t['outcome']) for t in sorted(world.systems.get('service_tasks',[]),key=lambda t:(t['status'] not in ('queued','working'),t['priority'],t['due'],t['id']))[:100]]))
        view['tables'].append(table('Finance comparisons',['Task','Lender','Principal','Term','APR','Estimated interest'],[(t['id'],names.get(q['lender'],q['lender']),money(q['principal']),str(q['months'])+' months',str(q['rate_bps']/100)+'%',money(q['estimated_interest'])) for t in world.systems.get('service_tasks',[]) for q in t.get('proposals',[])], 'Estimates use declining principal; financing is not committed by a report.'))
        view['tables'].append(table('Accounting work products',['Account','Prepared','Period starts','Revenue','Expenses','Profit','Cash'],[(names.get(r['business_id'],r['business_id']),r['date'],r['from_date'],money(r['revenue']),money(r['expenses']),money(r['profit']),money(r['cash'])) for r in world.systems.get('management_reports',[])[-30:]]))
        view['tables'].append(table('Legal results',['Task','Original offer','Documented concession','Cash recovered','Unresolved / outcome'],[(t['id'],money(t['original_offer'] or 0),money(t['improvement']),money(t['recovered']),t['outcome']) for t in world.systems.get('service_tasks',[]) if t['department']=='legal']))
        view['tables'].append(table('Employee directory for assignments',['Employment ID','Employee','Employer','Role'],[(emp.id,person_names[emp.person_id],names[emp.employer],next(p.role for p in world.positions if p.id==emp.position_id)) for emp in employees]))
        view['forms'].append(form('department_configure','Configure a staffed department','Tools cost $500 per level. Select employees by name, or leave blank for all qualified staff in the role. Creating a department provides no benefit by itself.',[field('provider','Employing business','','select',boptions),field('department','Department','hr','select',choices({k:k.upper() if k in ('hr','it') else k.title() for k in DEPARTMENTS})),field('staff','Assigned staff (none: all qualified role staff)',[],'multiselect',staff),field('tools','Tool level',1,'number',minimum=1,maximum=3),field('regions','Covered counties, comma separated','Rutland County'),field('industries','Industry expertise, comma separated','retail')]))
        targets={b.id:b.name for b in world.businesses if b.status=='market'}
        targets.update({p.id:p.name for p in world.properties if p.status=='market'})
        targets.update({l['id']:l['tenant_name']+' overdue rent' for l in world.systems['leases'] if l['arrears']>0})
        targets.update({emp.id:person_names[emp.person_id] for emp in employees})
        targets.update({c['id']:c['id']+' documented workmanship claim' for c in world.systems.get('legal_claims',[]) if c['status']=='open'})
        targets.update({r['id']:b.name+' overdue invoice' for b in businesses for r in b.receivables if r.get('defaulted') or r.get('overdue_since') or r['due']<world.date})
        view['forms'].append(form('service_request','Request service work','Outside work is reserved at $90 per hour. Mixed work uses internal staff and an outside reserve, refunding unused outside capacity. Negotiations can fail; future concessions are not cash.',[field('recipient','Receiving account',scope,'select',accounts),field('provider','Provider','outside','select',choices({'outside':'Outside specialists',**{b.id:b.name for b in businesses}})),field('department','Service','accounting','select',choices({k:v[0] for k,v in DEPARTMENTS.items()})),field('mode','Arrangement','outside','select',choices({'outside':'Outsourced','internal':'Internal','mixed':'Mixed'})),field('matter','Legal matter','negotiation','select',choices({k:k.title() for k in ('negotiation','collection','template','dispute')})),field('target_id','Transaction or employee target','','select',choices({'':'None / routine',**targets})),field('priority','Priority (1 highest)',2,'number',minimum=1,maximum=5),field('days','Deadline in days',14,'number',minimum=1,maximum=180)]))
        queued={t['id']:t['id']+' '+t['department'] for t in world.systems.get('service_tasks',[]) if t['status'] in ('queued','working')}
        view['forms'].append(form('outsource_service','Outsource unfinished work','Prepay only the remaining effort. Existing work and actual incurred costs are retained.',[field('task_id','Task','','select',choices(queued))]))
        view['forms'].append(form('service_priority','Reprioritize work','Changing priority does not create more staff time.',[field('task_id','Task','','select',choices(queued)),field('priority','Priority',1,'number',minimum=1,maximum=5)]))
    else:
        view.update(title='Property workbench',intro='Inspect existing condition, compare tenant proposals, plan work and market properties with explicit costs and uncertain sales.')
        rows=[]
        for p in props:
            income=world.systems.get('property_income_totals',{}).get(p.id,{})
            costs=world.systems.get('property_cost_totals',{}).get(p.id,{})
            leases=[l for l in world.systems['leases'] if l['property_id']==p.id and l['status']=='active']
            occupied=len(leases) if p.spaces else int(p.status in ('rented','occupied'))
            debt_paid=sum(h.get('paid',0) for loan in world.systems['loans'] if loan.get('property_id')==p.id for h in loan['history'])
            operating=income.get('earned',0)-costs.get('holding',0)-costs.get('repairs',0)
            cash=income.get('collected',0)-income.get('holding_paid',0)-income.get('work_paid',0)-debt_paid
            rows.append((p.name,income.get('since','Tracking begins next day'),money(income.get('collected',0)),money(operating),money(cash),str(occupied)+' / '+str(max(1,len(p.spaces))),money(sum(l['arrears'] for l in leases)),money(p.value)))
        view['tables'].append(table('Property operating results',['Property','Tracked since','Collected rent','Operating income','Cash after work, holding and debt','Occupied spaces','Rent receivable','Estimated value'],rows,'Actual tracked collections and cash payments. Deposits, acquisitions and sale proceeds are excluded. Unpaid internal contractor charges remain obligations in Operations.'))
        view['tables'].append(table('Funded flip commitments',['Property','Phase','Total capital committed','Unused reserve'],[(r['property_id'],r['phase'],money(r['committed']),money(r['reserve'])) for r in world.systems.get('flip_progress',{}).values()]))
        view['forms'] += [form('fund_flip','Acquire and fund planned flip','Inspect and prepare a budget first. Purchase plus renovation, contingency and holding reserves require cash now.',[field('property_id','Planned property','','select',allprops),field('entity','Investor',scope,'select',accounts)]),form('flip_work','Begin funded flip work','Uses the funded reserve for real interior contractor work. Cost overruns require more approved capital.',[field('property_id','Property','','select',poptions)]),form('add_flip_reserve','Approve additional flip capital','Transfers cash into the project reserve and increases its recorded commitment.',[field('property_id','Property','','select',poptions),field('amount_dollars','Additional reserve ($)',1000,'number',minimum=1)])]
        view['tables'].append(table('Systems and inspections',['Property','Category','Condition','Inspected systems / uncertainty'],[(p.name,p.category,p.condition,str(world.systems.get('inspections',{}).get(p.id,{}).get('readings','Not inspected'))+' +/-5' if p.id in world.systems.get('inspections',{}) else 'Not inspected') for p in props]))
        repair_rows=[]
        for p in props:
            if p.category=='land':continue
            for system in SYSTEMS:
                repair=PropertyOperations(e).quote(p,system,'repair');replacement=PropertyOperations(e).quote(p,system,'replacement')
                estimates=[money(q['total'])+' / '+str(q['downtime'])+' days / up to +'+str(q['gain'])+' condition' for q in (repair,replacement)]
                repair_rows.append((p.name+' / '+system,*estimates,repair['exposure']))
        view['tables'].append(table('Repair choices',['Property / system','Repair cost / time / benefit','Replacement cost / time / benefit','Deferral exposure'],repair_rows,'Outside estimates use reserved capacity of four hours per day. Internal completion depends on qualified staff availability; workmanship affects the final benefit. Replacement disrupts rent during work.'))
        view['tables'].append(table('Active and completed work',['Job','Property / system','Type / provider','Remaining effort','Actual cost','Status / quality'],[(j['id'],j['property_id']+' / '+j['system'],j['kind']+' / '+names.get(j['provider'],j['provider']),str(j['remaining'])+' min',money(j['actual_cost']),j['status']+' / '+str(j['quality'])) for j in world.systems.get('property_work',[])]))
        view['tables'].append(table('Tenant proposals',['Offer','Property / space','Rent / ceiling','Reliability','Required area','Allowance','Term','Status'],[(o['id'],o['property_id']+' / '+o['space_id'],money(o['rent'])+' / '+money(o['max_rent']),str(o['reliability'])+'/100',o['area'],money(o['improvement']),str(o['months'])+' months',o['status']) for o in world.systems.get('tenant_offers',[])]))
        view['tables'].append(table('Flip scenarios',['Property','Purchase','Renovation / contingency','Holding / schedule','Sale range','Downside / upper profit'],[(x['property_id'],money(x['purchase']),money(x['renovation'])+' / '+money(x['contingency']),money(x['holding'])+' / '+str(x['days'])+' days',money(x['sale_low'])+' — '+money(x['sale_high']),money(x['profit_low'])+' — '+money(x['profit_high'])) for x in world.systems.get('flip_budgets',{}).values()]))
        offers=[(p_id,o) for p_id,l in world.systems.get('property_listings',{}).items() for o in l['offers']]
        view['tables'].append(table('Property offers',['Property / offer','Price','Concession','Financing failure risk','Status'],[(pid+' / '+o['id'],money(o['price']),money(o['concession']),str(o['finance_risk'])+'%',o['status']) for pid,o in offers]))
        view['tables'].append(table('Completed project results',['Property','Sale proceeds','Debt paid','Cash returned','Project profit after costs'],[(x['property_id'],money(x['proceeds']),money(x['principal_and_interest']),money(x['cash_returned']),money(x['project_profit'])) for x in world.systems.get('property_listings',{}).values() if x['status']=='sold']))
        view['forms'].append(form('outsource_property_work','Outsource unfinished internal work','Prepay only remaining outside labor; existing materials and incurred internal costs remain recorded.',[field('property_id','Property','','select',poptions),field('work_id','Unfinished work','','select',choices({j['id']:j['id']+' / '+j['system'] for j in world.systems.get('property_work',[]) if j['status']=='working' and j['provider']!='outside'}))]))
        view['forms']+=[form('inspect_property','Inspect a property','A $350 inspection estimates preexisting system condition; repeated inspection does not create new defects.',[field('property_id','Property','','select',allprops),field('entity','Paying account',scope,'select',accounts)]),
            form('flip_budget','Prepare a flip budget','Scenarios include transaction fees, contingency and holding costs. No guaranteed appreciation or purchase commitment.',[field('property_id','Property','','select',allprops),field('entity','Investor',scope,'select',accounts),field('renovation_dollars','Renovation budget ($)',5000,'number',minimum=0),field('days','Schedule days',90,'number',minimum=7,maximum=730)]),
            form('property_work','Book property work','Materials are paid now. Outside labor is prepaid and consumed over working time. Internal labor uses actual employees at cost and reduces outside customer capacity.',[field('property_id','Property','','select',poptions),field('system','System','roof','select',choices({'all':'All systems needing repair',**{k:k.replace('_',' ').title() for k in SYSTEMS}})),field('kind','Work','repair','select',choices({k:k.title() for k in WORK})),field('provider','Contractor','outside','select',choices({'outside':'Outside contractor',**{b.id:b.name for b in businesses}})),field('use','Conversion use','residential','select',choices({k:k.replace('_',' ').title() for k in ('residential','commercial','office','mixed_use','industrial')}))]),
            form('advertise_space','Advertise a vacancy','Advertising costs $150 and takes five days. A vacant whole building is configured as one space if needed.',[field('property_id','Property','','select',poptions),field('space_id','Space ID (blank: first unit)'),field('rent_dollars','Asking monthly rent ($)',1000,'number',minimum=100)]),
            form('accept_tenant','Negotiate and accept a tenant','Respect the applicant rent ceiling and required area; allowances cost cash. Deposits remain liabilities.',[field('property_id','Property','','select',poptions),field('offer_id','Tenant offer','','select',choices({o['id']:o['id'] for o in world.systems.get('tenant_offers',[]) if o['status']=='open'})),field('rent_dollars','Agreed monthly rent ($)',1000,'number',minimum=100)]),
            form('renew_property_lease','Renew an expiring lease','Renewal opens 60 days before expiry. The tenant can reject excessive rent increases.',[field('property_id','Property','','select',poptions),field('lease_id','Lease','','select',choices({l['id']:l['tenant_name'] for l in world.systems['leases'] if l['status']=='active' and c.controlled(l['owner'])})),field('rent_dollars','Renewal monthly rent ($)',1000,'number',minimum=100)]),
            form('market_property','Market or reprice a property','Offers take time and lenders can refuse financing. Existing leases, receivables and protected deposits transfer to the buyer; tenant businesses remain independently owned.',[field('property_id','Property','','select',poptions),field('asking_dollars','Asking price ($)',100000,'number',minimum=100)]),
            form('accept_property_offer','Accept a sale offer','Closing takes 14 days. No sale proceeds are received before financing clears.',[field('property_id','Property','','select',poptions),field('offer_id','Sale offer','','select',choices({o['id']:o['id']+' / '+money(o['price']) for pid,o in offers if o['status']=='open'}))]),
            form('withdraw_property_sale','Rent instead of selling','Withdraw an uncommitted listing. Only suitable vacant spaces can then be leased.',[field('property_id','Property','','select',poptions)])]
        workflow=('inspect_property','flip_budget','fund_flip','flip_work','property_work','outsource_property_work','add_flip_reserve','advertise_space','accept_tenant','renew_property_lease','market_property','accept_property_offer','withdraw_property_sale')
        view['forms'].sort(key=lambda item:workflow.index(item['action']))
    from .service_project_views import extend
    extend(view,world,names,businesses,employees,props,scope)
    if page=='home_office':
        from .home_office_company import extend as extend_company
        extend_company(view,world,scope)
    from .property_scale_views import extend as scale_extend
    scale_extend(view,world,names,businesses,scope)
    return view
